#' @rdname Load_IMC_data
#' @title Load data generated by ImcSegmentationPipeline
#'   (https://github.com/BodenmillerGroup/ImcSegmentationPipeline)
#' @description This function loads data produced by the ImcSegmentationPipeline and output a list containing the different objects
#' @param Path_to_cell_file path to the Cell.csv file produced by the ImcSegmentationPipeline
#' @param Path_to_panel_file path to the panel.csv file
#' @param Name_target name of the column from the panel.csv file that provides the gene name
#' @param Name_metal name of the column from the panel.csv file that provides the metal name
#' @param Regex_expression_channel full prefix of the cell.csv file column name that describe marker intensity 
#' @param DNA_channel vector containing the name of the channels that measure cellular DNA amount 
#' @param Use_for_clustering which channels will be used for cell clustering 

#' @return Returns a list object that can later be used to build a SCE object
#'
#' @examples
#'List_data = Load_IMC_data("Desktop/analysis/cpout/cell.csv",
#'                          Path_to_panel_file ="Desktop/analysis/cpout/panel.csv",
#'                          DNA_channel = c("Iridium191","Iridium193"),
#'                          Regex_expression_channel = "Intensity_MeanIntensity_FullStackFiltered_c",
#'                          Use_for_clustering = c("Myeloperoxidase.MPO","CD31","SMA","Cytokeratin.5",
#'                                                 "Keratin.14","Vimentin","CD3","CD68", "Cytokeratin.8.18","CD45",
#'                                                 "Carbonic.Anhydrase.IX","Fibronectin","Ki.67","CD20","CD44","pan.Cytokeratin"))
#'
#' @import readr
#' @export


Load_IMC_data = function(Path_to_cell_file,Path_to_panel_file,
                         Name_target = "Target",Name_metal="Metal.Tag",
                         Regex_expression_channel = "Intensity_MeanIntensity_FullStackFiltered_c",
                         DNA_channel = NULL,Use_for_clustering = NULL) {
  
  Panel_table = read.csv(Path_to_panel_file)
  Panel_table = Panel_table[Panel_table$full==1,]
  
  
  cat("Loading the cell data ... ")
  Raw_data = readr::read_csv(Path_to_cell_file,progress = TRUE)
  Raw_data = as.data.frame(Raw_data)
  cat("done ! \n ")
  
  #Extracting the mean intensity values
  
  Expression_data = Raw_data[,base::grepl(colnames(Raw_data),pattern = Regex_expression_channel)]
  l = colnames(Expression_data)
  l = strsplit(l,split = Regex_expression_channel)
  l = unlist(lapply(l,FUN = function(x) {x[2]}))
  l = as.numeric(l)
  
  colnames(Expression_data) = make.names(Panel_table[l,Name_target],unique = TRUE)
  
  
  #Extracting the cell annotation table
  
  Cell_annotation = data.frame(ImageNumber = Raw_data$ImageNumber,
                               ObjectNumber = Raw_data$ObjectNumber,
                               Location_Center_X = Raw_data$Location_Center_X,
                               Location_Center_Y = Raw_data$Location_Center_Y,
                               Cell_size = Raw_data$AreaShape_Area)
  
  #Extracting the gene annotation table
  
  Gene_annotation = data.frame(Used_for_clustering = colnames(Expression_data)%in%Use_for_clustering,
                               DNA_channel = colnames(Expression_data)%in%DNA_channel,
                               row.names = colnames(Expression_data))
  return(list(Expression_data = Expression_data,
              Cell_annotation = Cell_annotation,
              Gene_annotation = Gene_annotation))
  
  
}
