#' @title Reads in single-cell data generated by the steinbock pipeline
#'
#' @description Reader function to generate a
#' \code{\linkS4class{SpatialExperiment}} or
#' \code{\linkS4class{SingleCellExperiment}} object from single-cell data
#' obtained by the [steinbock](https://github.com/BodenmillerGroup/steinbock)
#' pipeline.
#'
#' @param path full path to the steinbock output folder
#' @param intensities_folder name of the folder containing the intensity measurements per image
#' @param regionprops_folder name of the folder containing the cell-specific
#' morphology and spatial measurements per image. Can be set to \code{NULL} to 
#' exclude reading in morphology measures.
#' @param graphs_folder name of the folder containing the spatial connectivity
#' graphs per image. Can be set to \code{NULL} to exclude reading in graphs.
#' @param pattern regular expression specifying a subset of files that should 
#' be read in.
#' @param extract_cellid_from single character indicating which column entry in 
#' the intensity files contain the integer cell id.
#' @param extract_coords_from character vector indicating which column entries 
#' in the regionprobs files contain the x and y coordinates.
#' @param panel single character containing the name of the panel file. This can
#' either be inside the steinbock path (recommended) or located somewhere else.
#' @param extract_names_from single character indicating the column of the panel
#' file containing the channel names.
#' @param return_as should the object be returned as 
#' \code{\linkS4class{SpatialExperiment}} (\code{return_as = "spe"}) or
#' \code{\linkS4class{SingleCellExperiment}} (\code{return_as = "sce"}). 
#' @param BPPARAM parameters for parallelised processing. 
#' 
#' @return returns a \code{SpatialExperiment} or \code{SingleCellExperiment}
#' object markers in rows and cells in columns. 
#'
#' @section The returned data container:
#' In the case of __both__ containers \code{x}, intensity features are stored in
#' the \code{counts(x)} slot. Morphological features are stored in the
#' \code{colData(x)} slot. The graphs are stored as \code{\link[S4Vectors]{SelfHits}}
#' in the \code{colPair(x, "neighbourhood")} slot.
#' 
#' In the case of a returned \code{SpatialExperiment} object, the cell coordinates
#' are stored in the \code{spatialCoords(x)} slot.
#' 
#' In the case of a returned \code{SingleCellExperiment} object, the cell 
#' coordinates are stored in the \code{colData(x)} slot named as \code{Pos_X}
#' and \code{Pos_Y}.
#'
#' @examples
#' path <- system.file("extdata/mockData/steinbock", package = "imcRtools")
#' 
#' # Read in as SpatialExperiment object
#' x <- read_steinbock(path)
#' x
#' 
#' # Read in as SingleCellExperiment object
#' x <- read_steinbock(path, return_as = "sce")
#' x
#' 
#' # Read in a subset of files
#' x <- read_steinbock(path, pattern = "mockData1")
#' x
#' 
#' # Only read in intensities
#' x <- read_steinbock(path, graphs_folder = NULL, regionprops_folder = NULL)
#' x
#' 
#' # Parallelisation
#' x <- read_steinbock(path, BPPARAM = BiocParallel::bpparam())
#' 
#' @seealso 
#' \url{https://github.com/BodenmillerGroup/steinbock} for the pipeline
#' \code{\link{read_cpout}} for reading in single-cell data as produced by the
#' ImcSegmentationPipeline
#' \code{\link[SingleCellExperiment]{SingleCellExperiment}} and 
#' \code{\link[SpatialExperiment]{SpatialExperiment}} for the constructor 
#' functions.
#' 
#' @author Nils Eling (\email{nils.eling@@dqbm.uzh.ch})
#' 
#' @importFrom SpatialExperiment SpatialExperiment
#' @export
read_steinbock <- function(path,
                           intensities_folder = "cell_intensities",
                           regionprops_folder = "cell_regionprops",
                           graphs_folder = "cell_graphs",
                           pattern = NULL,
                           extract_cellid_from = "Object",
                           extract_coords_from = c("centroid-0", "centroid-1"),
                           panel = "panel.csv",
                           extract_names_from = "name",
                           return_as = c("spe", "sce"),
                           BPPARAM = SerialParam()){
    
    .valid.read_steinbock.input(path, intensities_folder, graphs_folder,
                                regionprops_folder, extract_cellid_from, 
                                extract_coords_from, panel, extract_names_from,
                                pattern)
    
    return_as <- match.arg(return_as)
    
    # Read intensities
    int_file_names <- list.files(file.path(path, intensities_folder),
                                 pattern = pattern, full.names = TRUE)
    object <- .read_intensities(x = int_file_names,
                                     cell_id = extract_cellid_from,
                                     return_as = return_as,
                                     BPPARAM = BPPARAM)
    
    # Read regionprobs
    if (!is.null(regionprops_folder)) {
        object <- .read_regionprobs(x = object,
                                    cur_path = file.path(path, regionprops_folder),
                                    cell_id = extract_cellid_from, 
                                    coords = extract_coords_from,
                                    return_as = return_as,
                                    BPPARAM = BPPARAM)
    }
    
    # Read graphs
    if (!is.null(graphs_folder)) {
        object <- .read_graphs(x = object,
                               cur_path = file.path(path, graphs_folder),
                               return_as = return_as,
                               BPPARAM = BPPARAM)
    }
    
    # Merge objects
    object <- do.call("cbind", object)
    
    # Add panel data
    object <- .add_panel(object, path, panel, extract_names_from = "name")
    
    return(object)
}
