#' @title Reads in single-cell data generated by the ImcSegmentationPipeline
#' 
#' @description Reader function to generate a
#' \code{\linkS4class{SpatialExperiment}} or
#' \code{\linkS4class{SingleCellExperiment}} object from single-cell data
#' obtained by the [ImcSegmentationPipeline](https://github.com/BodenmillerGroup/ImcSegmentationPipeline)
#' pipeline.
#'
#' @param path full path to the CellProfiler output folder

#' @return returns a \code{SpatialExperiment} or \code{SingleCellExperiment}
#' object markers in rows and cells in columns. 
#'
#' @examples
#' path <- system.file("extdata/mockData/cpout", package = "imcRtools")
#' 
#' # Read in as SpatialExperiment object
#' x <- read_cpout(path)
#' x
#' 
#' # Read in as SingleCellExperiment object
#' x <- read_cpout(path, return_as = "sce")
#' x
#' 
#' @author Tobias Hoch
#' @author Nils Eling (\email{nils.eling@@dqbm.uzh.ch})
#'
#' @import SingleCellExperiment
#' @importFrom S4Vectors DataFrame
#' @importFrom SummarizedExperiment colData<- rowData<- metadata<-
#' @export

read_cpout <- function(path,
                       object_file = "cell.csv",
                       image_file = "Image.csv",
                       panel_file = "panel.csv",
                       graph_file = "Object relationships.csv",
                       object_feature_file = "var_cell.csv",
                       intensities = "Intensity_MeanIntensity_FullStackFiltered",
                       extract_imgid_from = "ImageNumber",
                       extract_cellid_from = "ObjectNumber",
                       extract_coords_from = c("Location_Center_X", "Location_Center_Y"),
                       extract_cellmetadata_from = "Neighbors_NumberOfNeighbors_8",
                       extract_imagemetadata_from = c("Metadata_acname", "Metadata_acid", "Metadata_description"),
                       extract_metal_from = "Metal Tag",
                       scale_intensities = TRUE,
                       extract_scalingfactor_from = "Scaling_FullStack",
                       return_as = c("spe", "sce")){
    
    .valid.read_cpout.input(path, object_file, image_file,
                            panel_file, graph_file, object_feature_file,
                            intensities, 
                            extract_imgid_from, extract_cellid_from, 
                            extract_names_from, extract_coords_from
                            extract_cellmetadata_from, extract_imagemetadata_from,
                            extract_metal_from, scale_intensities,
                            extract_scalingfactor_from)
    
    return_as <- match.arg(return_as)
    
    object <- .cpout_create_object(path, object_file, image_file, 
                                   object_feature_file, 
                             intensities, extract_imgid_from,
                             extract_cellid_from, extract_coords_from,
                             extract_cellmetadata_from, 
                             scale_intensities, extract_scalingfactor_from)
    
    object <- .cpout_add_image_metadata(object, path, image_file, 
                                  extract_imagemetadata_from)
    
    object <- .cpout_add_graph(object, path, graph_file)
    
    object <- .add_panel(object, path, panel_file, extract_metal_from)
    
    return(object)

}
