#' @title Reads in single-cell data as generated by the seinbock pipeline
#'
#' @description Reader function to generate a
#' \code{\linkS4class{SpatialExperiment}} object from single-cell data
#' obtained by the [steinbock](https://github.com/BodenmillerGroup/steinbock)
#' pipeline.
#'
#' @param path 
#' @param return_as should the object be returned as 
#' \code{\linkS4class{SpatialExperiment}} (\code{return_as = "spe"}) or
#' \code{\linkS4class{SingleCellExperiment}} (\code{return_as = "sce"}). 
#' 
#' @return returns a \code{SpatialExperiment} or \code{SingleCellExperiment} object containing ...
#'
#' @examples
#' path <- system.file("extdata/mockData/steinbock", package = "imcRtools")
#' 
#' # Read in all images
#' x <- read_steinbock(path)
#' x
#' 
#' @seealso 
#' \url{https://github.com/BodenmillerGroup/steinbock} for the pipeline
#' \code{\link{read_cpout}} for reading in single-cell data as produced by the
#' ImcSegmentationPipeline
#' 
#' @author Nils Eling (\email{nils.eling@@dqbm.uzh.ch})
#' 
#' @importFrom SpatialExperiment SpatialExperiment
#' @export
read_steinbock <- function(path,
                           intensities_folder = "cell_intensities",
                           graphs_folder = "cell_graphs",
                           regionprops_folder = "cell_regionprops",
                           pattern = NULL,
                           extract_cellid_from = "Object",
                           extract_coords_from = c("centroid-0", "centroid-1"),
                           panel = "panel.csv",
                           extract_names_from = "name",
                           return_as = c("spe", "sce"),
                           BPPARAM = SerialParam()){
    
    .valid.read_steinbock.input(path, intensities_folder, graphs_folder,
                                regionprops_folder, extract_cellid_from, 
                                extract_coords_from, panel, extract_names_from,
                                pattern)
    
    return_as <- match.arg(return_as)
    
    # Read intensities
    int_file_names <- list.files(file.path(path, intensities_folder),
                                 pattern = pattern, full.names = TRUE)
    object <- .read_intensities(x = int_file_names,
                                     cell_id = extract_cellid_from,
                                     return_as = return_as,
                                     BPPARAM = BPPARAM)
    
    # Read regionprobs
    if (!is.null(regionprops_folder)) {
        object <- .read_regionprobs(x = object,
                                    cur_path = file.path(path, regionprops_folder),
                                    cell_id = extract_cellid_from, 
                                    coords = extract_coords_from,
                                    return_as = return_as,
                                    BPPARAM = BPPARAM)
    }
    
    # Read grpahs
    if (!is.null(graphs_folder)) {
        object <- .read_graphs(x = object,
                               cur_path = file.path(path, graphs_folder),
                               return_as = return_as,
                               BPPARAM = BPPARAM)
    }
    
    # Merge objects
    object <- do.call("cbind", object)
    
    # Add panel data
    object <- .add_panel(object, path, panel, extract_names_from = "name")
    
    return(object)
}
