#' @title Reads in single-cell data as generated by the seinbock pipeline
#'
#' @description Reader function to generate a
#' \code{\linkS4class{SpatialExperiment}} object from single-cell data
#' obtained by the [steinbock](https://github.com/BodenmillerGroup/steinbock)
#' pipeline.
#'
#' @param path 
#' @param return_as should the object be returned as 
#' \code{\linkS4class{SpatialExperiment}} (\code{return_as = "spe"}) or
#' \code{\linkS4class{SingleCellExperiment}} (\code{return_as = "sce"}). 
#' 
#' @return returns a \code{SpatialExperiment} or \code{SingleCellExperiment} object containing ...
#'
#' @examples
#' path <- system.file("extdata/mockData/steinbock", package = "imcRtools")
#' 
#' # Read in all images
#' x <- read_steinbock(path)
#' x
#' 
#' @seealso 
#' \url{https://github.com/BodenmillerGroup/steinbock} for the pipeline
#' \code{\link{read_cpout}} for reading in single-cell data as produced by the
#' ImcSegmentationPipeline
#' 
#' @author Nils Eling (\email{nils.eling@@dqbm.uzh.ch})
#' 
#' @importFrom SpatialExperiment SpatialExperiment
#' @export
read_steinbock <- function(path,
                           intensities_folder = "cell_intensities",
                           graphs_folder = "cell_graphs",
                           regionprops_folder = "cell_regionprops",
                           cell_id = "Object",
                           coords = c("centroid-0", "centroid-1"),
                           panel = "panel.csv",
                           pattern = NULL,
                           return_as = c("spe", "sce"),
                           BPPARAM = SerialParam()){
    
    .valid.read_steinbock.input()
    
    return_as <- match.arg(return_as)
    
    # Read intensities
    int_file_names <- list.files(file.path(path, intensities_folder),
                                 pattern = pattern, full.names = TRUE)
    cur_objects <- .read_intensities(x = int_file_names,
                                     cell_id = cell_id,
                                     return_as = return_as,
                                     BPPARAM = BPPARAM)
    
    # Read regionprobs
    if (!is.null(regionprops_folder)) {
        cur_objects <- .read_regionprobs(x = cur_objects,
                                         cur_path = file.path(path, regionprops_folder),
                                         cell_id = cell_id, 
                                         coords = coords,
                                         return_as = return_as,
                                         BPPARAM = BPPARAM)
    }
    
    # Read grpahs
    if (!is.null(graphs_folder)) {
        cur_objects <- .read_graphs(x = cur_objects,
                                    cur_path = file.path(path, graphs_folder),
                                    return_as = return_as,
                                    BPPARAM = BPPARAM)
    }
    
    # Merge objects
    cur_objects <- do.call("cbind", cur_objects)
    
    
    
    if (!is.null(panel)) {
        if (file.exists(file.path(path, panel))) {
            cur_panel <- vroom(file.path(path, panel), 
                               progress = FALSE, 
                               col_types = cols())
        } else if (file.exists(panel)) {
            cur_panel <- vroom(panel, 
                               progress = FALSE, 
                               col_types = cols())
        } else {
            warning("'panel' does not exist.")
            next
        }
        
        if ("keep" %in% colnames(cur_panel)) {
            cur_panel <- cur_panel %>% filter(keep == 1)
        }
        
        cur_panel <- cur_panel[match(rownames(object), cur_panel$name),]
        
        rowData(object) <- cur_panel
    }
    
    return(spe)
}
