name: build-checks-devel

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: 
        - devel

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container: rocker/r-ver:devel

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bioconductor and install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            BiocManager
            rcmdcheck
            BiocCheck
            sf
            concaveman
            svglite
          needs: vignette

      - name: Check
        run: |
          install.packages("rcmdcheck")          
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
        
      - name: BiocCheck
        run: |
          BiocManager::install("BiocCheck")
          BiocCheck::BiocCheck(".")
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}
